[project]
name = "asl-classifier-cnn"
version = "0.1.0"
description = "Real-time ASL Alphabet Recognizer"
authors = [
    {name = "Ordinary33", email = "husnie.baddie@g.msuiit.edu.ph"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"

dependencies = [
    "opencv-python>=4.9.0",
    "scikit-learn>=1.4.0",
    "tqdm>=4.66.0",
    "numpy>=1.26.0",
    "pillow>=10.0.0",
    "torch>=2.4.0",
    "torchvision>=0.19.0",
    "mediapipe>=0.10.14",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel>=6.29.0",
    "matplotlib>=3.8.0",
    "seaborn>=0.13.0",
    "nbstripout>=0.7.0",
    "flake8>=7.0.0",
    "pre-commit>=3.5.0",
    "mypy>=1.8.0",
    "notebook>=7.0.0"
]

[[tool.poetry.source]]
name = "pytorch_cu126"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"

[tool.poetry.dependencies]
torch = {source = "pytorch_cu126"}
torchvision = {source = "pytorch_cu126"}

[tool.mypy]
explicit_package_bases = true
namespace_packages = true
ignore_missing_imports = true

[tool.poetry]
package-mode = false